apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 2 # tells deployment to run 2 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/dtc-attendee210/internal-image:v1.0.0
        env: 
        - name: GOOGLE_CLOUD_PROJECT
          value: "dtc-attendee210"
        ports:
        - containerPort: 8082
            
        
